from turtle import*
#Нарисовать ананас
import turtle
turtle.shape("turtle") 
turtle.speed(0.5) 
turtle.color("yellow") 
turtle.pencolor("black") 
turtle.begin_fill() 
turtle.circle(50, 360) 
turtle.end_fill() 
# turtle.end_fill() 
turtle.up() 
turtle.left(90) 
turtle.forward(25) 
turtle.forward(50) 
turtle.right(90) 
turtle.forward(25) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(30, 360) 
turtle.end_fill() 
turtle.right(180) 
turtle.up() 
turtle.forward(25) 
turtle.down() 
turtle.right(180) 
turtle.begin_fill() 
turtle.circle(30, 360) 
turtle.end_fill() 
turtle.right(180) 
turtle.up() 
turtle.forward(25) 
turtle.down() 
turtle.right(180) 
turtle.begin_fill() 
turtle.circle(30, 360) 
turtle.end_fill() 
 
turtle.right(90) 
turtle.up() 
turtle.forward(25) 
turtle.right(270) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(30, 360) 
turtle.end_fill() 
turtle.up() 
turtle.forward(50) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(30, 360) 
turtle.end_fill() 
 
turtle.up() 
turtle.right(180) 
turtle.forward(25) 
turtle.right(90) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(27, 360) 
turtle.end_fill() 
turtle.right(180) 
turtle.begin_fill() 
turtle.circle(27, 360) 
turtle.end_fill() 
 
turtle.up() 
turtle.forward(50) 
turtle.right(270) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(27, 360) 
turtle.end_fill() 
turtle.up() 
turtle.right(270) 
turtle.forward(85) 
 
turtle.right(90) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(30, 360) 
turtle.end_fill() 
 
 
 
turtle.color("green") 
# turtle.fillcolor("black") 
turtle.pencolor("black") 
turtle.up() 
turtle.right(270) 
turtle.forward(60) 
turtle.right(90) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(40, 360, 4) 
turtle.end_fill() 
turtle.up() 
turtle.forward(10) 
turtle.right(90) 
turtle.forward(4) 
turtle.left(90) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(40, 360, 4) 
turtle.end_fill() 
turtle.pencolor("black") 
turtle.up() 
turtle.forward(10) 
turtle.right(90) 
turtle.forward(4) 
turtle.left(90) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(40, 360, 4) 
turtle.end_fill() 
turtle.pencolor("black") 
turtle.up() 
turtle.forward(7) 
turtle.right(90) 
turtle.forward(4) 
turtle.left(90) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(40, 360, 4) 
turtle.end_fill() 
turtle.pencolor("black") 
turtle.up() 
turtle.forward(10) 
turtle.right(90) 
turtle.forward(4) 
turtle.left(90) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(40, 360, 4) 
turtle.end_fill() 
turtle.pencolor("black") 
 
turtle.up() 
turtle.right(180) 
turtle.forward(75) 
 
turtle.up() 
# turtle.forward(10) 
turtle.right(270) 
# turtle.forward(4) 
turtle.left(90) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(40, 360, 4) 
turtle.end_fill() 
turtle.pencolor("black") 
turtle.up() 
turtle.forward(10) 
# turtle.right(0) 
turtle.forward(4) 
turtle.left(90) 
turtle.forward(4) 
turtle.right(90) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(40, 360, 4) 
turtle.end_fill() 
turtle.pencolor("black") 
turtle.up() 
turtle.forward(10) 
# turtle.right(0) 
turtle.forward(4) 
turtle.left(90) 
turtle.forward(4) 
turtle.right(90) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(40, 360, 4) 
turtle.end_fill() 
turtle.pencolor("black") 
turtle.up() 
turtle.forward(10) 
# turtle.right(0) 
turtle.forward(4) 
turtle.left(90) 
turtle.forward(4) 
turtle.right(90) 
turtle.down() 
turtle.begin_fill() 
turtle.circle(40, 360, 4) 
turtle.end_fill() 
turtle.pencolor("black") 
 
turtle.up() 
turtle.left(90) 
turtle.forward(99) 
turtle.left(180) 
 
 
 
# turtle.width 
turtle.exitonclick()